### ISSUE TITLE
Clip without defined a_max

### ISSUE THREAD

**Issue by GeorgePearse** [baal-org/baal#211]
https://github.com/ElementAI/baal/blob/798f6e3668d73c476013dcdc4aca8f54c3420b28/baal/active/heuristics/stochastics.py#L45

This line is causing me issues.  Will try setting a_max to None, but I'm not sure of the implications relative to the intent.

```
Traceback (most recent call last):
  File "main.py", line 226, in <module>
    run(model, baal_trainer, baal_data_module, config, experiment_name)
  File "main.py", line 212, in run
    should_continue = baal_trainer.step(model, datamodule=baal_data_module)
  File "/workspace/environments/active-learning/lib/python3.8/site-packages/baal/utils/pytorch_lightning.py", line 202, in step
    to_label = self.heuristic(probs)
  File "/workspace/environments/active-learning/lib/python3.8/site-packages/baal/active/heuristics/heuristics.py", line 258, in __call__
    return self.get_ranks(predictions)[0]
  File "/workspace/environments/active-learning/lib/python3.8/site-packages/baal/active/heuristics/stochastics.py", line 45, in get_ranks
    distributions = np.clip(distributions, 0)
  File "<__array_function__ internals>", line 4, in clip
TypeError: _clip_dispatcher() missing 1 required positional argument: 'a_max'
```

Will try to submit PR for the string mapping mentioned in previous issue shortly (https://github.com/ElementAI/baal/issues/210).

**Comment by Dref360** [comment]
Closed in #213
