### ISSUE TITLE
Problem when importing baal 1.7.0 with Python 3.7

### ISSUE THREAD

**Issue by DManowitz** [baal-org/baal#244]
**Describe the bug**
You say that baal supports Python >= 3.7.  However, when I try to import baal 1.7.0, I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\lib\site-packages\baal\__init__.py", line 1, in <module>
    from .active.dataset import ActiveLearningDataset
  File "C:\...\lib\site-packages\baal\active\__init__.py", line 4, in <module>
    from .active_loop import ActiveLearningLoop
  File "C:\...\lib\site-packages\baal\active\active_loop.py", line 12, in <module>
    from .dataset import ActiveLearningDataset
  File "C:\...\lib\site-packages\baal\active\dataset\__init__.py", line 1, in <module>
    from .numpy import ActiveNumpyArray
  File "C:\...\lib\site-packages\baal\active\dataset\numpy.py", line 6, in <module>
    from baal.active.dataset.base import SplittedDataset
  File "C:\...\lib\site-packages\baal\active\dataset\base.py", line 2, in <module>
    from typing import Union, List, Optional, Any, TYPE_CHECKING, Protocol
ImportError: cannot import name 'Protocol' from 'typing' (C:\Users\manow\miniconda3\envs\py37_ml_TfGpuMain\lib\typing.py)
```

Protocol is not included in the typing library in Python 3.7.

**To Reproduce**
Install baal 1.7.0 in a Python 3.7 environment.  Start Python and try to import baal.

Some advices:
* Please don't use custom data or custom paths.
* Use random arrays or even np.ones, np.zeros.
* The example should run with Baal (and deps) alone.
* Should be Python3 compatible.
* Should not be OS specific.
* The file should reproduce the bug with **high* fidelity.
* Link to a gist would be appreciated.

**Expected behavior**
baal imports properly

**Vesion (please complete the following information):**
 - OS: Windows 10
 - Python: 3.7
 - Baal version: 1.7.0

**Additional context**

**Comment by Dref360** [comment]
Ah good catch! We only support 3.8.

I updated the README in [this commit](https://github.com/baal-org/baal/commit/016d1740d0db0a4b316d316e138c959a5a41ecf8)

Thank you!
